config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "homes#home"
  resource :homes, only: [:create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/home.rb
class Home < ApplicationRecord
  validates :name, :email, :text, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def home
  end

  def create
    @home = Home.new(home_params)
    if @home.save
      HomeMailer.send_mail(@home).deliver_now
      redirect_to root_path, notice: "送信しました。"
    end
  end

  private
  def home_params
    params.permit(:name, :email, :text)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/home.html.slim
.top
  .top__flash
    - if flash[:notice]
      .top__flash-notice
        = flash[:notice]
  .top__wrap
    .top__wrap-fade{data-aos="fade-in", data-aos-delay="300"}
      h2 TAKUMU NAKAJIMA
      p.top__wrap--detail This is my first portfolio
      = link_to "お問い合わせ", {}, class: "top-contact"
.about
  .about__wrap
    .about__wrap__left{data-aos="fade-right"}
      = image_tag "https://motor-fan.jp/images/articles/10005239/big_559198_201808141133380000001.jpg", class: "about-image"
      .about__wrap__left--name
        p Takumu Nakajima
        p 中島　拓夢
      .about__wrap__left--birth
        p 1999.6.28
    .about__wrap__right{data-aos="fade-left"}
      h2 Profile
      .about__wrap__right--text
        p バイクと音楽が好きな大阪出身の20歳。
        p 今年三月にTECH::EXPERTを卒業し、4ヶ月ほど大阪のスタートアップでインターンをしていました。
      .about__wrap__right--text
        p 東京のweb系自社開発企業への就職を志望しており、日々精進しています。
      .about__wrap__right__sns
        = link_to "https://twitter.com/jima_engineer", class: "about__wrap__right__sns--twitter", target: "_blank"
          = icon "fab", "twitter-square", class: "twitter"
        = link_to "https://www.facebook.com/gt.vo.5", class: "about__wrap__right__sns--facebook", target: "_blank"
          = icon "fab", "facebook", class: "facebook"
.works
  .works--title{data-aos="fade-up"}
    h2 WORKS
    p 実積
  .works__perfomances{data-aos="fade-up"}
    .perfomance
      = image_tag "pictweet.png", class: "works--image"
      h2 TECH::EXPERT カリキュラム
      p 画像投稿アプリ
    .perfomance
      = image_tag "chatspace.png", class: "works--image" 
      h2 TECH::EXPERT カリキュラム
      p 非同期通信チャットアプリ
    .perfomance
      = link_to "https://docs.google.com/document/d/1M6vAGhC72_fT_hJlaaOKaHK57u72ZREBy7Qy0oIaBik/edit#", class: "perfomance__link", target: "_blank"
        = image_tag "merukari.png", class: "works--image" 
        h2 TECH::EXPERT チーム開発
        p メルカリ模倣サイト
    .perfomance
      = image_tag "portfolio.png", class: "works--image" 
      h2 ポートフォリオ
      p 現在ご覧いただいているサイト
    .perfomance
      = link_to "https://lienlien.work/about", class: "perfomance__link", target: "_blank"
        = image_tag "lien.png", class: "works--image"
        h2 個人アプリ
        p チャットアプリ
    .perfomance
      = image_tag "gudenal.png", class: "works--image" 
      h2 インターン
      p 新規プロジェクト
    .perfomance
      = link_to "http://gude.osaka", class: "perfomance__link", target: "_blank"
        = image_tag "gude_hp.png", class: "works--image" 
        h2 インターン
        p hp改修
  .works__github{data-aos="fade-up"}
    = link_to "https://github.com/cb50one", class: "works__github__link", target: "_blank"
      = icon "fab", "github", class: "github"
      p githubはこちら
.skills
  .skills--title{data-aos="fade-up"}
    h2 SKILLS
    p 技術
  .skills__list{data-aos="zoom-in"}
    table
      tr
        th 
          p 言語
        td HTML5/CSS3, JavaScript, ruby
      tr
        th 
          p フレームワーク・ライブラリ
        td jquery, Ruby on Rails
      tr
        th 
          p インフラ
      tr
        th 
          p aws
        td 
          p VPC/ec2/IAM/S3/RDS(mysql)/Route53
          p SAA試験に向け勉強中です。
      tr
        th 
          p その他
      tr
        th 
          p Docker
        td 現在、勉強中です。
.contact
  .contact--title{data-aos="fade-up"}
    h2 CONTACT
    p お問い合わせ
  .contact__form{data-aos="fade-up"}
    = form_with url: homes_path, local: true, html: {id: "form-validate"} do |f| 
      .form-group
        = f.label :名前
        span.required 必須
        br/
        = f.text_field :name, placeholder: "name", class: "validate[required]", "data-prompt-position": "inline"
      .form-group
        = f.label :メールアドレス
        span.required 必須
        br/
        = f.text_field :email, placeholder: "email address", class: "validate[required, custom[email]]", "data-prompt-position": "inline"
      .form-group
        = f.label :内容
        span.required 必須
        br/
        = f.text_area :text, placeholder: "content", class: "validate[required]", "data-prompt-position": "inline"
      .form-group
        = f.submit "送信する", class: "contact-btn"

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"]
    title
      | TAKUMU NAKAJIMA
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = favicon_link_tag 'https://motor-fan.jp/images/articles/10005239/big_559198_201808141133380000001.jpg'
    = analytics_init if Rails.env.production?
  body
    = yield